<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FournisseursTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('fournisseurs')->insert([
            [
                'neq' => 1140030355,
                'courriel' => 'info@cirquedusoleil.com',
                'password' => bcrypt('password123'),
                'nomEntreprise' => 'Cirque du Soleil',
                'num_rbq' => 'RBQ00001',
                'numCivique' => '8400',
                'rue' => '2e Avenue',
                'bureau' => '',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'codePostal' => 'H1Z4M6',
                'siteInternet' => 'http://www.cirquedusoleil.com',
                'régionAdministrative' => 'Montréal',
                'TypeNumTelephone' => 'Bureau',
                'numéroTelephone' => 5141234567,
                'poste' => '101',
                'courrielContact' => 'info@cirquedusoleil.com',
                'numTPS' => 123456789,
                'numTVQ' => 987654321,
                'conditionPaiement' => '30 jours net',
                'devise' => 'CAD',
                'modeCommunication' => 'Courriel'
            ],
            [
                'neq' => 1168420345,
                'courriel' => 'info@cascades.com',
                'password' => bcrypt('password123'),
                'nomEntreprise' => 'Cascades Canada ULC',
                'num_rbq' => 'RBQ00002',
                'numCivique' => '772',
                'rue' => 'Sherbrooke Est',
                'bureau' => 'Bureau 400',
                'ville' => 'Kingsey Falls',
                'province' => 'Québec',
                'codePostal' => 'J0A1B0',
                'siteInternet' => 'http://www.cascades.com',
                'régionAdministrative' => 'Centre-du-Québec',
                'TypeNumTelephone' => 'Bureau',
                'numéroTelephone' => 8191234567,
                'poste' => '201',
                'courrielContact' => 'info@cascades.com',
                'numTPS' => 234567891,
                'numTVQ' => 876543219,
                'conditionPaiement' => '60 jours net',
                'devise' => 'CAD',
                'modeCommunication' => 'Téléphone'
            ],
            [
                'neq' => 1143313945,
                'courriel' => 'contact@bombardier.com',
                'password' => bcrypt('password123'),
                'nomEntreprise' => 'Bombardier Inc.',
                'num_rbq' => 'RBQ00003',
                'numCivique' => '800',
                'rue' => 'René-Lévesque Blvd W',
                'bureau' => 'Bureau 2900',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'codePostal' => 'H3B1Y8',
                'siteInternet' => 'http://www.bombardier.com',
                'régionAdministrative' => 'Montréal',
                'TypeNumTelephone' => 'Bureau',
                'numéroTelephone' => 5148767900,
                'poste' => '301',
                'courrielContact' => 'contact@bombardier.com',
                'numTPS' => 345678912,
                'numTVQ' => 765432198,
                'conditionPaiement' => '45 jours net',
                'devise' => 'CAD',
                'modeCommunication' => 'Courriel'
            ],
            [
                'neq' => 1142249510,
                'courriel' => 'support@loblaw.ca',
                'password' => bcrypt('password123'),
                'nomEntreprise' => 'Les Compagnies Loblaw Ltée',
                'num_rbq' => 'RBQ00004',
                'numCivique' => '1',
                'rue' => 'Avenue Président-Kennedy',
                'bureau' => '',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'codePostal' => 'H2X3Y5',
                'siteInternet' => 'http://www.loblaw.ca',
                'régionAdministrative' => 'Montréal',
                'TypeNumTelephone' => 'Bureau',
                'numéroTelephone' => 5149874000,
                'poste' => '401',
                'courrielContact' => 'support@loblaw.ca',
                'numTPS' => 456789123,
                'numTVQ' => 654321987,
                'conditionPaiement' => '30 jours net',
                'devise' => 'CAD',
                'modeCommunication' => 'Téléphone'
            ],
            [
                'neq' => 1168030340,
                'courriel' => 'contact@cae.com',
                'password' => bcrypt('password123'),
                'nomEntreprise' => 'CAE Inc.',
                'num_rbq' => 'RBQ00005',
                'numCivique' => '8585',
                'rue' => 'Côte-de-Liesse',
                'bureau' => 'Bureau 100',
                'ville' => 'Deschaillons-sur-Saint-Laurent',
                'province' => 'Québec',
                'codePostal' => 'H4T1G6',
                'siteInternet' => 'http://www.cae.com',
                'régionAdministrative' => 'Montréal',
                'TypeNumTelephone' => 'Bureau',
                'numéroTelephone' => 5143416789,
                'poste' => '501',
                'courrielContact' => 'contact@cae.com',
                'numTPS' => 567891234,
                'numTVQ' => 543219876,
                'conditionPaiement' => '60 jours net',
                'devise' => 'CAD',
                'modeCommunication' => 'Téléphone'
            ],
            [
                'neq' => 1140045612,
                'courriel' => 'info@videotron.com',
                'password' => bcrypt('password123'),
                'nomEntreprise' => 'Vidéotron Ltée',
                'num_rbq' => 'RBQ00006',
                'numCivique' => '612',
                'rue' => 'Rue Saint-Jacques',
                'bureau' => '',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'codePostal' => 'H3B1B7',
                'siteInternet' => 'http://www.videotron.com',
                'régionAdministrative' => 'Montréal',
                'TypeNumTelephone' => 'Bureau',
                'numéroTelephone' => 5143804666,
                'poste' => '601',
                'courrielContact' => 'info@videotron.com',
                'numTPS' => 678912345,
                'numTVQ' => 432198765,
                'conditionPaiement' => '30 jours net',
                'devise' => 'CAD',
                'modeCommunication' => 'Courriel'
            ],
            [
                'neq' => 1143207234,
                'courriel' => 'contact@bell.ca',
                'password' => bcrypt('password123'),
                'nomEntreprise' => 'Bell Canada',
                'num_rbq' => 'RBQ00007',
                'numCivique' => '1',
                'rue' => 'Rue Carillon',
                'bureau' => '',
                'ville' => 'Montréal',
                'province' => 'Québec',
                'codePostal' => 'H1N3B7',
                'siteInternet' => 'http://www.bell.ca',
                'régionAdministrative' => 'Montréal',
                'TypeNumTelephone' => 'Bureau',
                'numéroTelephone' => 5148704000,
                'poste' => '701',
                'courrielContact' => 'contact@bell.ca',
                'numTPS' => 789123456,
                'numTVQ' => 321987654,
                'conditionPaiement' => '30 jours net',
                'devise' => 'CAD',
                'modeCommunication' => 'Téléphone'
            ],
        ]);
    }
}
